version: '3.2'
services:
    mysql5.7:
        build: ./databases/mysql5.7 # Image location to DockerFile
        container_name: mysql5.7
        restart: always
        ports:
            - 3306:3306
        volumes:
            - '/home/docker/mysql5.7:/var/lib/mysql' # Data location to persist

    mysql8:
        build: ./databases/mysql8 # Image location to DockerFile
        container_name: mysql8
        restart: always
        ports:
            - 3307:3306
        volumes:
            - '/home/docker/mysql8:/var/lib/mysql' # Data location to persist

    redis:
        build: ./redis # Image location to DockerFile
        container_name: redis
        restart: always
        ports:
            - 6379:6379
